version: '3'

# production

networks:
  pokezen:
    ipam:
      config:
        - subnet: 10.42.84.0/24

services:
  mongodb:
    image: mongo:4.1.7-xenial
    hostname: mongodb
    networks:
      - pokezen
    ports:
      - 27017
    environment:
      MONGO_INITDB_DATABASE: pokezen

  scalapi:
    build: ./back
    image: pokezen-back:latest
    hostname: scalapi
    networks:
      - pokezen
    ports:
      - 51264:9000

  reactfront:
    build: ./front
    image: pokezen-front:latest
    hostname: reactfront
    networks:
      - pokezen
    ports:
      - 51265:51265
