version: '3'

# production

networks:
  pokezen:
    ipam:
      config:
        - subnet: 10.16.0.0/24

services:
  scalapi:
    build: ./back
    image: pokezen-back:latest
    hostname: scalapi
    networks:
      - pokezen
    ports:
      - 51264:9000

  reactfront:
    build: ./front
    image: pokezen-front:latest
    networks:
      - pokezen
    ports:
      - 51265:51265
